### ISSUE TITLE
SeaMonkey integration?

### ISSUE THREAD

**Issue by NiveusLuna** [kylehuff/webpg-firefox#2]
Could you make this available for SeaMonkey, by chance? I'm gonna grab the XPI and hack on it myself, see what I can do, but it'd be nice if the upstream version (you) supported it.

If you'd rather just let me do it and hand you appropriate patches, I am happy to do so.

**Comment by NiveusLuna** [comment]
I think I have all the javascript code updated over at my repo fork. https://github.com/NiveusLuna/webpg-firefox

The XUL code appears to work decently, as well. I haven't tried testing beyond getting the extension to load and importing GPG keys.

GPG key import produces an error in the console saying that the plugin is undefined. The NPAPI plugin appears to need adjustment to see SeaMonkey as compatible. It detects SeaMonkey 2.13 as Firefox 2.

**Comment by kylehuff** [comment]
I am currently tasked out for the next 24 hours or so, but will certainly look at this issue (and your related changes).

As for the NPAPI plugin, it should be fairly universal; if it detects it as being hosted in Firefox, it should work. However, I have not done any testing with SeaMonkey. I will investigate further and if needed, create a relevant issue in the repo for the plugin and reference it here.

I appreciate your initiative on this, and will certainly support a working SeaMonkey integration within the primary appliacation, once we get it functioning.

**Comment by kylehuff** [comment]
@NiveusLuna, the commit referenced above should implement the extension for SeaMonkey to the same degree of functionality available in Firefox.

As you can see from the commit, I went about the integration different than in your branch, and I think it will have better support for the entire Mozilla line once polished.

Also, the reason why you were unable to access the plugin within SeaMonkey despite your changes is because the firefoxOverlay.xul file was not being loaded, due to a difference in how the overlay is applied to the browser via the chrome.manifest file (for example, in Firefox, the main browser XUL is browser.xul, and in SeaMonkey, it is navigator.xul). I did not have to make any changes to the NPAPI plugin or how it is accessed/referenced, just how the overlay XUL file is applied.

Again, I appreciate your efforts on this, even if I wasn't able to use your changes as-is. I encourage you to refresh/rebase your fork and continue to explore new features/implementations. I am eager to make this extension versatile and useful on a variety of platforms/browsers.

I look forward to working with you on future features/issues.

**Comment by NiveusLuna** [comment]
Oh, _wow_, I feel embarrassed. I completely forgot to check for that. I'll give it a look-see during my lunch break. I may code for a living, but it's on games, not on browser extensions. XD

**Comment by kylehuff** [comment]
heh, it happens. I do extension work all the time, and I didn't immediately know what was going on.

Anyway, I just made another commit; somewhere along the lines I dropped one of my changes out of the commit referenced in this issue, but it should work now.
